CREATE DATABASE task15

USE task15

-- 1) AUTO COMMIT AND AUTO ROLL BACK

CREATE TABLE DEMO
(
ID INT PRIMARY KEY,
NAME VARCHAR(25)
)

--success (AUTO COMMIT)

INSERT INTO DEMO VALUES
(1,'Peter'),
(1,'England')

-- AUTO ROLLBACK (THE STATEMENT WILL WE TERMINATED BCOZ HERE PRIMARY KEY IS VIOLATED)



-- 2) Implicit transactions


SET IMPLICIT_TRANSACTIONS ON 
INSERT INTO DEMO VALUES (1,'BEN'),(2,'MEE')

SELECT IIF(@@OPTIONS & 2 = 2,'IMPLICIT ON','IMPLICIT OFF') AS ISIMPLICITON

SELECT
	@@TRANCOUNT AS TRANSACTION_COUNT -- return1

COMMIT

SELECT
	@@TRANCOUNT AS AFTER_TRANSACTION_COUNT	--return 0 because transaction is commited

SET IMPLICIT_TRANSACTIONS OFF

-- 3. Explicit transactions
-- a. Only Commit - insert statement

BEGIN TRAN

INSERT INTO DEMO VALUES (3,'AARON'),(4,'RAMSEY')

SELECT
@@TRANCOUNT AS TRANSACTION_COUNT -- RETURNS 1 BECAUSE TRANSACTION IS ACTIVE

COMMIT

SELECT
@@TRANCOUNT AS AFTER_TRANSACTION_COUNT --RETURNS 0 BECAUSE TRANSACTION IS COMMITTED

-- b. Only Rollback - update statement

BEGIN TRAN 

SELECT * FROM DEMO

UPDATE 
	DEMO
SET
	ID=5 WHERE ID=4

SELECT * FROM DEMO 

ROLLBACK TRAN 

SELECT * FROM DEMO

-- C. Savepoint
BEGIN TRAN
UPDATE DEMO SET NAME='NANDUS' WHERE ID=4

INSERT INTO DEMO VALUES (5,'MARTINEZ')

SAVE TRANSACTION UPDATE_INSERT 

DELETE DEMO WHERE ID=2

SELECT * FROM DEMO

ROLLBACK TRAN UPDATE_INSERT

COMMIT

SELECT * FROM DEMO